name: stocks_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cached_network_image: 3.3.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  flex_color_scheme: ^7.3.1
  google_fonts: ^4.0.3
  firebase_crashlytics: ^3.4.8
  firebase_analytics: ^10.7.4
  localstore: ^1.3.5
  http: ^0.13.6
  provider: ^6.0.4
  shimmer: ^3.0.0
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  min_sdk_android: 20
  image_path: assets/images/logo.png
  adaptive_icon_foreground: assets/images/logo.png
  adaptive_icon_background: "#000000"

flutter_native_splash:
  ios: false
  web: false
  color: "#000000"
  image: assets/images/logo.png
  android12:
    color: "#000000"
    branding: assets/images/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/empty.png
    - assets/images/illustration.png
    - assets/images/error.png
    - assets/images/gone.png

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic


