// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5FTyZzsDffq8acHLubblDABghWbmc1cc',
    appId: '1:692186409368:web:ea107eb11332d978d2a3ed',
    messagingSenderId: '692186409368',
    projectId: 'stocks-app-woc',
    authDomain: 'stocks-app-woc.firebaseapp.com',
    storageBucket: 'stocks-app-woc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkZ1fJPL2XpZ2umn2MIoF6k32yQzxulTE',
    appId: '1:692186409368:android:95af1bb239001cd8d2a3ed',
    messagingSenderId: '692186409368',
    projectId: 'stocks-app-woc',
    storageBucket: 'stocks-app-woc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB10B2-NlgKmE42hvS-lBdT4MzjsskX0F0',
    appId: '1:692186409368:ios:51a343de45d835d9d2a3ed',
    messagingSenderId: '692186409368',
    projectId: 'stocks-app-woc',
    storageBucket: 'stocks-app-woc.appspot.com',
    iosBundleId: 'com.example.stocksApp',
  );
}
